Lesson 4
========================================================

***

### 1 e 2. Price vs x

```{r}
setwd("~/R/udacity scripts/lesson4")
library(ggplot2)
data("diamonds")
str(diamonds)

ggplot(aes(x=x,y=price),data=diamonds) +
  geom_point(alpha=1/40,position = position_jitter(h=0.1)) +
  xlim(3,quantile(diamonds$x,0.90)) +
  ylim(0,quantile(diamonds$price,0.90))
```

***

### 3. Correlations
```{r}
with(diamonds,cor.test(x = x, y = price, method = 'pearson'))
with(diamonds,cor.test(x = y, y = price, method = 'pearson'))
with(diamonds,cor.test(x = z, y = price, method = 'pearson'))
```

***

### 4. price vs depth
```{r}
ggplot(aes(x=depth,y=price),data=diamonds) +
  geom_point(alpha=1/100) +
  scale_x_continuous(breaks=seq(40,80,2))
```

***

### 7. Correlation price vs depth
```{r}
with(diamonds,cor.test(x = depth, y = price, method = 'pearson'))
```

***

### 8. price vs carat omit top 1%
```{r, fig.width= 12, fig.height= 6}
ggplot(aes(x=carat,y=price),data=diamonds) +
  geom_point(alpha=1/40,position = 'jitter') +
  xlim(0,quantile(diamonds$carat,0.99)) +
  ylim(0,quantile(diamonds$price,0.99))
```

***

### 9. scatterplot price x volume
```{r, fig.width= 12, fig.height= 6}
diamonds$volume <- diamonds$x * diamonds$y * diamonds$z

ggplot(aes(x=volume,y=price),data=diamonds) +
  geom_point()
```

***

### 11. Correlation price x volume
```{r, fig.width= 12, fig.height= 6}
with(subset(diamonds, volume != 0 & volume < 800),cor.test(price,volume))
```

***

### 12. Adjusts to scatterplot price x volume
```{r, fig.width= 8, fig.height= 4}
ggplot(aes(x=volume,y=price),data=subset(diamonds, volume != 0 & volume < 800)) +
  geom_point(alpha=1/40) +
  geom_smooth(method="lm", se = FALSE)
```

***

### 13. Diamonds by Clarity 
```{r}
library(dplyr)
diamondsByClarity <- diamonds %>% 
  group_by(clarity) %>%
  summarise(mean_price = mean(price),
            median_price = median(price),
            min_price = min(price),
            max_price = max(price),
            n = n())
```

***

### 14. Creating two bar plots in one graph
```{r}
diamonds_by_clarity <- group_by(diamonds, clarity)
diamonds_mp_by_clarity <- summarise(diamonds_by_clarity, mean_price = mean(price))

diamonds_by_color <- group_by(diamonds, color)
diamonds_mp_by_color <- summarise(diamonds_by_color, mean_price = mean(price))

library(gridExtra)
p1 <- ggplot(data = diamonds_mp_by_clarity) + geom_bar(aes(x=clarity,y=mean_price),stat = 'sum') 
p2 <- ggplot(data = diamonds_mp_by_color) + geom_bar(aes(x=color,y=mean_price),stat = 'sum')

grid.arrange(p1,p2)
```


